#! /bin/sh

exec sxhkd &
numlockx &
nitrogen --restore &
picom &
eww open bar &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#24273a"
bspc config active_border_color "#ed8796"
bspc config focused_border_color "#c6a0f6"

bspc config presel_feedback_color "#b7bdf8"

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

bspc config single_monocle	     false
